# Reproducible pipeline. Every reported number is regenerated by:
#   make setup models data train eval bench report
# (or `make all`). MODEL=<name> restricts `make train` to one model.

PY      ?= uv run --no-project --python .venv/bin/python python
export PYTHONPATH := $(CURDIR)/src
WORKERS ?= 4
MODEL   ?= all
MODELS  := $(if $(filter all,$(MODEL)),rule lstm gru lstm_attention tcn stgcn,$(MODEL))
YOLO_URL := https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n-pose.pt

.PHONY: all setup models data download extract prepare train eval bench report test smoke clean-smoke

all: models data train eval bench report

setup:
	uv venv --python 3.11 .venv
	uv pip install --python .venv/bin/python -r requirements.txt

models: models/yolov8n-pose.pt
models/yolov8n-pose.pt:
	mkdir -p models && curl -fsSL -o $@ $(YOLO_URL)

# video -> keypoints (.npz) -> windows/splits cache -> reports/01_data.md
data: download extract prepare

download:
	$(PY) -m pose_estimation.preprocessing.urfall download

extract: models
	$(PY) -m pose_estimation.preprocessing.urfall extract --device cpu

prepare:
	$(PY) -m pose_estimation.experiments.run prepare
	$(PY) -m pose_estimation.experiments.data_stats

# MODEL=rule|lstm|gru|lstm_attention|tcn|stgcn|all ; fixed split + 5-fold CV, seeds from config.yaml
train:
	$(PY) -m pose_estimation.experiments.run train --models $(MODELS) --workers $(WORKERS)

eval:
	$(PY) -m pose_estimation.experiments.run collect

bench:
	$(PY) -m pose_estimation.experiments.bench

report:
	$(PY) -m pose_estimation.experiments.report

test:
	$(PY) -m pytest -q tests

# End-to-end code check on synthetic stand-in data (never reported as a result).
smoke:
	$(PY) -m pose_estimation.experiments.synthetic --root dataset/synthetic
	$(PY) -m pose_estimation.experiments.run prepare --pose-dir dataset/synthetic/pose --raw-dir dataset/synthetic/raw \
		--cache dataset/synthetic/cache/prepared.pkl --splits-out dataset/synthetic/splits.json
	$(PY) -m pose_estimation.experiments.run train --cache dataset/synthetic/cache/prepared.pkl --runs-dir runs_smoke \
		--protocols fixed --seeds 0 --epochs 2 --workers $(WORKERS)

clean-smoke:
	rm -rf dataset/synthetic runs_smoke
